name: Paperify CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    name: Test paperify
    runs-on: ubuntu-latest
    env:
      IMG_HELP_MESSAGE: "UNPACK: zbarimg --raw -Sbinary -1 FILENAME.jpg | head -c 2953 > paperify.tgz"
    steps:
      - name: Install packages
        run: sudo apt-get install qrencode zbar-tools imagemagick
      - uses: actions/checkout@v2
      - name: Generate test files
        run: |
          echo "Generating testfine.bin"
          dd if=/dev/urandom of=testfile.bin bs=1 count=10240
          sha1sum testfile.bin
          echo "Test file generated! running paperify.sh"
      - name: Paperify
        run: ./paperify.sh testfile.bin
      - name: Digitallify
        run: ./digitallify.sh testfile.regen.bin testfile.bin-qr
      - name: Check if both digitallified is same as original
        run: diff testfile.bin testfile.regen.bin
      - run: echo "Tests were successful. diff exit code $?"
      - name: Package paperify using paperify
        run: |
          tar cfz paperify.tgz README.md paperify.sh digitallify.sh
          ./paperify.sh -c "$IMG_HELP_MESSAGE" paperify.tgz
          mv paperify.tgz-qr/paperify.tgz-000.png paperify.tgz.png
